//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26.09.2020 08:19:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace vdrControlCenterModel
{
    public partial class Station {

        public Station()
        {
            OnCreated();
        }

        public virtual long RecId { get; set; }

        public virtual string MachineName { get; set; }

        public virtual string HostAddress { get; set; }

        public virtual int StationType { get; set; }

        public virtual string Description { get; set; }

        public virtual int? SSHPort { get; set; }

        public virtual string SSHUserName { get; set; }

        public virtual string SSHPassword { get; set; }

        public virtual int? SVDRPPort { get; set; }

        public virtual string SambaUserName { get; set; }

        public virtual string SambaPassword { get; set; }

        public virtual string PathToRecordings { get; set; }

        public virtual int? VdrControlServicePort { get; set; }

        public virtual string MacAddress { get; set; }

        public virtual bool? EnableWOL { get; set; }

        public virtual int? VDRAdminPort { get; set; }

        public virtual string VDRAdminUserName { get; set; }

        public virtual string VDRAdminPassword { get; set; }

        public virtual StationType StationType1 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
