//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26.09.2020 08:19:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace vdrControlCenterModel
{
    public partial class Recording {

        public Recording()
        {
            OnCreated();
        }

        public virtual long RecId { get; set; }

        public virtual DateTime? Modtime { get; set; }

        public virtual int? Number { get; set; }

        public virtual DateTime? RecordingTime { get; set; }

        public virtual int? Duration { get; set; }

        public virtual string Title { get; set; }

        public virtual string RecordingPath { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
