//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26.09.2020 08:19:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace vdrControlCenterModel
{
    public partial class StatusInfo {

        public StatusInfo()
        {
            OnCreated();
        }

        public virtual long RecId { get; set; }

        public virtual int? TotalDiskSpace { get; set; }

        public virtual int? FreeDiskSpace { get; set; }

        public virtual decimal? UsedPercent { get; set; }

        public virtual long SystemSettingsRecId { get; set; }

        public virtual SystemSetting SystemSetting { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
