//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26.09.2020 08:19:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace vdrControlCenterModel
{
    public partial class Channel {

        public Channel()
        {
            this.EPGs = new List<EPG>();
            this.Timers = new List<Timer>();
            OnCreated();
        }

        public virtual long RecId { get; set; }

        public virtual DateTime Modtime { get; set; }

        public virtual int? Number { get; set; }

        public virtual string ChannelID { get; set; }

        public virtual string ChannelName { get; set; }

        public virtual string ProviderName { get; set; }

        public virtual int? Frequency { get; set; }

        public virtual string Parameter { get; set; }

        public virtual string SignalSource { get; set; }

        public virtual int? SymbolRate { get; set; }

        public virtual string VPID { get; set; }

        public virtual string APID { get; set; }

        public virtual string TPID { get; set; }

        public virtual string CAID { get; set; }

        public virtual string SID { get; set; }

        public virtual string NID { get; set; }

        public virtual string TID { get; set; }

        public virtual string RID { get; set; }

        public virtual string Params { get; set; }

        public virtual bool? Favourite { get; set; }

        public virtual IList<EPG> EPGs { get; set; }

        public virtual IList<Timer> Timers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
