//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26.09.2020 08:19:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace vdrControlCenterModel
{
    public partial class SystemSetting {

        public SystemSetting()
        {
            this.MachineName = @"";
            this.StatusInfos = new List<StatusInfo>();
            OnCreated();
        }

        public virtual long RecId { get; set; }

        public virtual string MachineName { get; set; }

        public virtual short? ChannelListType { get; set; }

        public virtual bool? FavouritesOnly { get; set; }

        public virtual bool? SaveBufferToFile { get; set; }

        public virtual bool? EnableLogging { get; set; }

        public virtual DateTime? LastUpdateChannels { get; set; }

        public virtual DateTime? LastUpdateEPG { get; set; }

        public virtual DateTime? LastUpdateTimers { get; set; }

        public virtual DateTime? LastUpdateRecordings { get; set; }

        public virtual DateTime? LastUpdateStatus { get; set; }

        public virtual IList<StatusInfo> StatusInfos { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
