//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26.09.2020 08:19:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace vdrControlCenterModel
{
    public partial class StationType {

        public StationType()
        {
            this.Stations = new List<Station>();
            OnCreated();
        }

        public virtual int RecId { get; set; }

        public virtual string StationType1 { get; set; }

        public virtual IList<Station> Stations { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
