USE [master]
GO

/****** Object:  Database [vdrControlCenter_Test]    Script Date: 02.10.2020 18:20:59 ******/
CREATE DATABASE [vdrControlCenter_Test]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'vdrControlCenter', FILENAME = N'D:\data\mssql\vdrControlCenter_Test.mdf' , SIZE = 860160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'vdrControlCenter_log', FILENAME = N'D:\data\mssql\vdrControlCenter_Test_log.ldf' , SIZE = 4988928KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vdrControlCenter_Test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vdrControlCenter_Test] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET ARITHABORT OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vdrControlCenter_Test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vdrControlCenter_Test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET  DISABLE_BROKER 
GO

ALTER DATABASE [vdrControlCenter_Test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vdrControlCenter_Test] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vdrControlCenter_Test] SET  MULTI_USER 
GO

ALTER DATABASE [vdrControlCenter_Test] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vdrControlCenter_Test] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vdrControlCenter_Test] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [vdrControlCenter_Test] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [vdrControlCenter_Test] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [vdrControlCenter_Test] SET QUERY_STORE = OFF
GO

ALTER DATABASE [vdrControlCenter_Test] SET  READ_WRITE 
GO


